/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Euler */

#ifndef _Included_Euler
#define _Included_Euler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Euler
 * Method:    sinFromC
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Euler_sinFromC
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
