/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProcessInfo */

#ifndef _Included_ProcessInfo
#define _Included_ProcessInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProcessInfo
 * Method:    getProcessID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ProcessInfo_getProcessID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
